# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimalWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('pressure', models.FloatField()),
                ('skycover', models.FloatField()),
                ('water_avail', models.FloatField()),
                ('humiditiy', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_degree', models.FloatField()),
                ('rain_forecast', models.CharField(max_length=20000)),
            ],
        ),
    ]
